### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by java-james** [pradeep1991singh/react-native-secure-key-store#108]
Hi when can we expect a new release to include changes such as: https://github.com/pradeep1991singh/react-native-secure-key-store/commit/4bb26d8907b2ab3953d3ff31f39d5bf1538c76ae

**Comment by pradeep1991singh** [comment]
Hi @java-james 
thanks for reminder
https://github.com/pradeep1991singh/react-native-secure-key-store/releases/tag/v2.0.10

**Comment by ray-holland-es** [comment]
Why is this closed? It still has not been published.
