### ISSUE TITLE
Keystore not working for android

### ISSUE THREAD

**Issue by shadrech** [pradeep1991singh/react-native-secure-key-store#24]
<img width="310" alt="screen shot 2018-03-28 at 12 08 35" src="https://user-images.githubusercontent.com/6001129/38025584-cbdea6f8-3280-11e8-8508-b996c78b7238.png">
Keep getting this error on android:
Failed to load generated key pair from keystore.
This is when I try and write to key store

**Comment by olfek** [comment]
Same for me

**Comment by olfek** [comment]
This was happening to me because the variable I was using for the key was `undefined`. It worked as expected after I fixed this.
