### ISSUE TITLE
android not compiling even example app

### ISSUE THREAD

**Issue by irfman12** [pradeep1991singh/react-native-secure-key-store#25]
He @pradeep1991singh 

I have the following in my app, and from example app android doesn't compile
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",

what is the min required versions of react and react-native, I don't see that in the actual package.json checked in of the base build, it's in the example.

:react-native-secure-key-store:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/h267226/work/react-native-secure-key-store/example/node_modules/react-native-secure-key-store/android/src/main/java/com/reactlibrary/securekeystore/RNSecureKeyStorePackage.java:18: error: RNSecureKeyStorePackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNSecureKeyStorePackage implements ReactPackage {
       ^
Note: /Users/h267226/work/react-native-secure-key-store/example/node_modules/react-native-secure-key-store/android/src/main/java/com/reactlibrary/securekeystore/RNSecureKeyStoreModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-secure-key-store:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-secure-key-store:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by irfman12** [comment]
Okay so reading through I see your breaking change, I have an issue I can't upgrade from 0.44 to 0.47 in my app

**Comment by pradeep1991singh** [comment]
@irfman12  then try to use old release e.g. `<= v1.0.5`.

**Comment by irfman12** [comment]
@pradeep1991singh  hey, I am testing v1.0.5 now.  What will I lose between 1.0.5 and 1.0.9 . Are there major bug fixes, between the versions?

**Comment by pradeep1991singh** [comment]
Not much.
