### ISSUE TITLE
Using sharedPreferences instead of Storage and using KeyGenParameterSpec for later versions of Android

### ISSUE THREAD

**Issue by karthikpala** [pradeep1991singh/react-native-secure-key-store#26]
Hi @pradeep1991singh , Thanks for the awesome project.

Sorry for opening this as an issue. Could you let us know why we are using Storage and creating files to store keys instead of storing them in shared preferences in private mode?

Also regarding the usage of KeyPairGeneratorSpec, since it is deprecated are you planning to use KeyGenParameterSpec for later versions of android (M+). I can submit a PR if you want me to.

**Comment by pradeep1991singh** [comment]
@karthikpala PR is most welcome.

**Comment by pradeep1991singh** [comment]
Waits for your PR, closing this issue for now.
