### ISSUE TITLE
Opps ! `value` can not be object ??!??

### ISSUE THREAD

**Issue by anhhtz** [pradeep1991singh/react-native-secure-key-store#28]
Opps, `value` can not be `object` (like `JSON`) ?!?? Just a `string` only ?

**Comment by pradeep1991singh** [comment]
Yes, it is. 
Any issue in the libraries not working as expected/told?

**Comment by Bang9** [comment]
> Opps, `value` can not be `object` (like `JSON`) ?!?? Just a `string` only ?

use JSON.stringify and JSON.parse

**Comment by isaaclem** [comment]
@Bang9 , @pradeep1991singh  Regarding this, is there any limit on what's the max characters we can store?
