### ISSUE TITLE
Public Key expiration date

### ISSUE THREAD

**Issue by oximer** [pradeep1991singh/react-native-secure-key-store#4]
Why are you setting a end date for the key?

KeyPairGeneratorSpec spec = new KeyPairGeneratorSpec.Builder(getContext())
                                        .setAlias(alias)
                                        .setSubject(new X500Principal("CN=" + alias))
                                        .setSerialNumber(BigInteger.ONE)
                                        .setStartDate(start.getTime())
                                        .setEndDate(end.getTime()).build();

How to handle it once it expires?

**Comment by pradeep1991singh** [comment]
@oximer Increase to 50Yrs in new release `1.0.7`
