### ISSUE TITLE
Warning Module RNSecureKeyStore requires main queue setup since it overrides 'init'

### ISSUE THREAD

**Issue by faisalahmedansari20** [pradeep1991singh/react-native-secure-key-store#48]
I just integrated this library. And i am getting this warning.

`Module RNSecureKeyStore requires main queue setup since it overrides 'init' but doesn't implement 'requiresMainQueueSetup'. In a future release React Native will defualt to initializing all native modules on a background thread explicitly opted-out of.`

**Comment by theneilmeister** [comment]
Adding the following to ios/RNSecureKeyStore.m fixes this issue:

`
+ (BOOL)requiresMainQueueSetup
{
    return NO;
}
`

**Comment by pradeep1991singh** [comment]
Fixed in the latest release, closing this issue.
