### ISSUE TITLE
When is going to be released a new version?

### ISSUE THREAD

**Issue by dimun** [pradeep1991singh/react-native-secure-key-store#51]

**Comment by hefgi** [comment]
+1

@pradeep1991singh we need https://github.com/pradeep1991singh/react-native-secure-key-store/issues/48 to be released.

**Comment by pradeep1991singh** [comment]
Done, should be visible in npm registry.

**Comment by hefgi** [comment]
Can we have https://github.com/pradeep1991singh/react-native-secure-key-store/pull/49 as well released ? it doesn't build on Android
