### ISSUE TITLE
[Android] Error while finalizing cipher

### ISSUE THREAD

**Issue by wtr7** [pradeep1991singh/react-native-secure-key-store#7]
On android I receive this error while calling the get function. RNSecureKeyStore is defined.

`{"code":1,"api-level":23,"message":Error while finalizing cipher}`

### Versions
"react": "16.0.0-alpha.12"
"react-native": "0.47.2"

Android 6.0

**Comment by pradeep1991singh** [comment]
@wtr7 RNSecureKeyStore version?

**Comment by wtr7** [comment]
1.0.6

**Comment by pradeep1991singh** [comment]
@wtr7  Fixed in release `1.0.7`

**Comment by bohdansushchak** [comment]
Please reopen
I have similar issue on android, but when i set data to RNSecureKeyStore
{"code":9,"api-level":23,"message":Error while finalizing cipher} 

"react": "16.9.0",
"react-native": "0.61.5",
"react-native-secure-key-store": "2.0.9",

Device: Honor 5X Android 6.0.1
