### ISSUE TITLE
Typechecking issue in consuming project

### ISSUE THREAD

**Issue by davidgovea** [pradeep1991singh/react-native-secure-key-store#74]
Was experiencing this with typescript `3.7.3`, but also just confirmed that this happens on latest `3.8.2` as well.

```

../node_modules/react-native-secure-key-store/index.d.ts:2:29 - error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

  2   export const ACCESSIBLE = {
                                ~
  3     AFTER_FIRST_UNLOCK: 'AccessibleAfterFirstUnlock',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 11     WHEN_UNLOCKED_THIS_DEVICE_ONLY: 'AccessibleWhenUnlockedThisDeviceOnly',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 12   }
    ~~~

../node_modules/react-native-secure-key-store/index.d.ts:16:52 - error TS2749: 'ACCESSIBLE' refers to a value, but is being used as a type here.

16     set: (key: string, value: string, accessible?: ACCESSIBLE) => Promise<any>
                                                      ~~~~~~~~~~


Found 2 errors.
```

As a workaround, the consuming project can specify `"skipLibCheck": true` in their `tsconfig.json`.

I plan to make a PR -- wanted to record the error here.

**Comment by djMax** [comment]
Any luck on this? I don't love running patch-package every time...

**Comment by davidgovea** [comment]
Thanks for the ping @djMax. Made a quick PR #80 

Is that a similar approach to the patchfile you're using? I haven't tested my PR in a consuming project yet, but the change is straightforward, and a ["string enum"](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) seems appropriate here.
