### ISSUE TITLE
podspec is inside the ios folder

### ISSUE THREAD

**Issue by AmirHMousavi** [pradeep1991singh/react-native-secure-key-store#76]
BUG REPORT:

The `RNSecureKeyStore.podspec`  is placed inside the `ios` folder of the package. This causes auto-linking and afterward, `pod install `face error and we should change the path manually to target the `ios` folder inside the module

where the **podspec should be** placed:
`pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store'`

Where **it is** placed
`pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store/ios'`

**Comment by davidgovea** [comment]
I don't believe there is a bug here. The `ios` folder is a valid place for the podspec, since that's where the Xcode project is.

> all libraries need to ship a Podspec either in the root of their folder **or where the Xcode project is**.

Source: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-ios

Also anecdotally, I haven't encountered any autolinking issues.

**Comment by anchi20** [comment]
+1 on the autolinking issue @AmirHMousavi .

**Comment by karanwadhwa** [comment]
+1 on the auto linking issue 
had to update the path in my podfile after linking
```ruby
pod 'RNSecureKeyStore', :path => '../node_modules/react-native-secure-key-store/ios'
```
without it this is the error I get:
```bash
[!] No podspec found for `RNSecureKeyStore` in `../node_modules/react-native-secure-key-store`
```

**Comment by aiden-petersen** [comment]
> I don't believe there is a bug here. The `ios` folder is a valid place for the podspec, since that's where the Xcode project is.
> 
> > all libraries need to ship a Podspec either in the root of their folder **or where the Xcode project is**.
> 
> Source: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#platform-ios
> 
> Also anecdotally, I haven't encountered any autolinking issues.

The cli has since changed and no longer supports the `link` command or having the podspec outside the root folder. New apps using react-native 0.69.0+ will no longer be able to link in this library due to the changes in the cli. I've made a PR to add auto-linking, looking for approval [110](https://github.com/pradeep1991singh/react-native-secure-key-store/pull/110)
